### ISSUE TITLE
cannot load page source code

### ISSUE THREAD

**Issue by Test-Acount** [stephenjtong/rss#3]
test url: https://bbs.instrument.com.cn/forum_499.htm
shows "302 Found"

**Comment by stephenjtong** [comment]
[image: image.png]

This website is quite special. Upon first access, it performs a 302
redirect and
issues a cookie, which must be included in subsequent requests in order to
obtain the webpage content. Modifying this behavior from my end would
require a very low-level approach that could affect all feeds, and would
require extensive testing. Perhaps you could use an intermediary page to
address this issue.

**Comment by stephenjtong** [comment]
<img width="545" alt="image" src="https://github.com/stephenjtong/rss/assets/541568/af030a34-72cb-4f57-86ce-bc350d958deb">


This website is quite special. Upon first access, it performs a 302
redirect and
issues a cookie, which must be included in subsequent requests in order to
obtain the webpage content. Modifying this behavior from my end would
require a very low-level approach that could affect all feeds, and would
require extensive testing. Perhaps you could use an intermediary page to
address this issue.

Additionally, this website has strong anti-scraping measures in place.

<img width="679" alt="image" src="https://github.com/stephenjtong/rss/assets/541568/65642d64-5921-4ac1-bc8c-c16c336efb26">

**Comment by stephenjtong** [comment]
Fixed:
<img width="1135" alt="image" src="https://github.com/stephenjtong/rss/assets/541568/72deb5b3-651a-4aa7-80f2-d226e7a37317">

**Comment by Test-Acount** [comment]
> Fixed: <img alt="image" width="1135" src="https://user-images.githubusercontent.com/541568/247844499-72deb5b3-651a-4aa7-80f2-d226e7a37317.png">

Very helpful. Thanks.
